#   Copyright 2015 Australian National Botanic Gardens
#
#   This file is part of the NSL Editor.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# encoding: utf-8
HelpTopic.create!([
  { lock_version: 1, created_by: "creator", marked_up_text: "You can switch off automatic wildcards for a search.\n  * Start your search term with a caret character (<em>&nbsp;^&nbsp;) to switch off the leading wildcard.\n  * Finish your search term with the dollar character (<em>&nbsp;$&nbsp;) to switch off the trailing wildcard.\n  * For example,\n      * <em>^flora is searched as <em>flora*</em>, ie. field must start with 'flora'\n      * <em>flora$ is searched as <em>*flora</em>, ie. field must end with 'flora', and\n      * <em>^flora$ is searched as <em>flora</em> and will therefore match only those fields that consist solely of 'flora'.\n\n  * You can think of these special characters as <em>anchors:\n    <ul class=\"indent\">\n      * caret (<em>&nbsp;^&nbsp;) <em>anchors</em> your search text to the beginning of the field, and\n      * dollar sign (<em>&nbsp;$&nbsp;) <em>anchors</em> you search text to the end of the field.\n\n\n", name: "Anchored Searching", sort_order: 40, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "\nCreate records\n  * When you create a record, NSL gives you a new record that you can edit in the usual way.\n  * The new record will appear in the details editing area.\n  * Create a new blank record by clicking\n  <%= link_to \"here\", '#', :class=>'create-reference-link', :'data-path'=>references_path %>.\n\n  * You can also create a new record as a copy of the current record by clicking\n  <%= link_to \"here\", '#', :class=>'copy-and-load-reference-link', :'data-path'=>references_path %>.\n  * Don't worry if your newly created record disappears if you view another record:  you can retrieve records by specifying how long ago they were created. e.g. <%= link_to \"Created today\", references_search_path(:query=>\"cr-a:1\") %>\n ", name: "Create", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: " Editing records\n  *\n ", name: "Edit", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "Example search for a reference\n=======================\n* Enter a word into the search field.  e.g. flora\n* Press enter or click the search button.\n\n", name: "Example Search for a Reference", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 1, created_by: "creator", marked_up_text: "\r\nFrequently asked questions\r\n  *Are the search field specifiers a bit short and cryptic?\r\n    Yes, but we want them to be easy to type and we think they're worth having because they add such flexibility and power to searching.\r\n\r\n  * What happens if I misspell a search field specifier?\r\n    It will be ignored and listed in the ignored criteria for that search.\r\n\r\n  * What happens if I enter a search field specifier without any associated criterion ie. an empty search field specifier?\r\n    It will be ignored and listed in the ignored criteria for that search.\r\n\r\n  * Can I search for \":\" in a text field?\r\n    No. It will be interpreted as marking a search field specifier.\r\n\r\n", name: "FAQ", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "\nHistory of Searching\n  * Check your browser history to revisit earlier searches.\n  * Each search is entered into the browser history with identifying details.\n  * Remember that rerunning a query at a different time could give different results.\n\n", name: "History of Searching", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "\nMoving around the page\n  *\n", name: "Move", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "\nSearch results are sorted alphabetically by citation\n  * You get a simple list of up to 200 entries. ie. the list is not paginated\n  * You can scroll up and down the list.\n  * Click on any record in the list to view its details.\n", name: "Results of Searching", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "\nSample advanced searches\n<table class=\"popup-menu-options\">\n  <tr><td><%= link_to \"Authored by Bentham in the 1830s\", references_search_path(:query=>\"a:bentham y:183\")%></tr>\n  <tr><td><%= link_to \"Authored by Bentham and Hooker\", references_search_path(:query=>\"a:bentham a:hooker\")%></tr>\n  <tr><td><%= link_to \"Published in 1843\", references_search_path(:query=>\"y:1843\")%></tr>\n  <tr><td><%= link_to \"Parent title contains 'flora of australia'\", references_search_path(:query=>\"pt:flora of australia\")%></tr>\n  <tr><td><%= link_to \"Published in the 1980s and parent title contains 'flora of australia'\", references_search_path(:query=>\"pt:flora of australia y:198\")%></tr>\n  <tr><td><%= link_to \"Created in the last week\", references_search_path(:query=>\"cr-a:7\")%></tr>\n  <tr><td><%= link_to \"Created in the last year and updated in the last week\", references_search_path(:query=>\"cr-a:365 upd-a:7\")%></tr>\n  <tr><td><%= link_to \"Created more than a year ago and updated in the last 30 days\", references_search_path(:query=>\"cr-b:365 upd-a:30\")%></tr>\n</table>\n", name: "Sample Advanced Searching", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 6, created_by: "creator", marked_up_text: "#### Searching ignores letter case\r\n\r\nSearching ignores the case of letters. i.e. whether they are upper-case or lower-case.\r\n\r\nFor example, the following search terms all match each other:\r\n\r\n- flora\r\n- fLorA\r\n- FLORA\r\n- Flora\r\n", name: "Searching ignores letter case", sort_order: 30, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "\nTips for searching\n  * NSL searches are designed to be quick and therefore \"cheap\" - if you have an idea for a search, it should be easy to run the search quickly.\n  * Start with quick broad searches and narrow down your result by adding criteria once you have a result set.\n  * Sketching your searches in step by step is often better than trying to enter a complex set of search conditions all at once.\n  * Most importantly, it reduces the risk of false-negative results due to mistaken expectations or even spelling errors in your search criteria.\n  * Better to start with a set of results and narrow them down than end up with an unexplained or misleading empty set.\n\n", name: "Tips for Searching", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "\nYour text search terms are automatically topped and tailed with wildcards.\n  * This is important because all NSL information is stored in fields, and search terms are matched against the whole of the relevant field.\n  * Automatic leading and trailing wildcards effectively relax this requirement meaning you can enter fragments of text as search terms without worrying about what else is in the field.  This makes searching easier and quicker and helps avoid false negative results.\n  * For example, if you search for <em>flora, the application will silently apply wildcards to match all records with <em>flora</em> anywhere in the search field.  This is normally exactly how you want search to work.\n  * You can also enter your own wildcards. e.g. <em>colo*r retrieves <em>color</em> and <em>colour</em> and <em>CoLOaR</em> and even <em>Colonial de Marseille</em>\n    <%= link_to \"(show me).\", references_search_path(:query=>\"colo*r\")%>\n  * You can use either <em>* or <em>%</em> as multi-character wildcards.  They mean the same thing.\n  * White space is trimmed from each end of any search string before the wildcards are added.\n", name: "Wildcard Searching", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "Fields you can specify for searching authors\n========================================\n| Field Name | Descriptor | Notes |\n|:-----------|:------------|:------------|\n| Name String            |        n: |\n|APNI ID| apni:| Does not distinguish between APNI Refs or Pubs link_to\n| Created after     | cr-a:     |    Supply number of days, no wildcards\n| Created before     | cr-b:     |    Supply number of days, no wildcards\n| Updated after     | cr-a:     |    Supply number of days, no wildcards\n| Updated before     | cr-b:     |    Supply number of days, no wildcards\n\n\n", name: "Fields for Searching Authors", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "Getting Help\n=========\nYou can find help for the NSL Editor on the Help page.", name: "Getting Help", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "Fields you can specify for searching help topics\n====================================\n Field Name | Descriptor | Notes |\n|:-----------|:------------|:------------|\n| Name            |        n: |\n| Created after     | cr-a:     |    Supply number of days, no wildcards\n| Created before     | cr-b:     |    Supply number of days, no wildcards\n| Updated after     | cr-a:     |    Supply number of days, no wildcards\n| Updated before     | cr-b:     |    Supply number of days, no wildcards  ", name: "Fields for Searching Help Topics", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "Tabbing on Reference details fails.  e.g. on the second edit tab, bottom field, tabbing takes you back to search results.\n", name: "Bug", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 14, created_by: "creator", marked_up_text: "Starting on the Name page\r\n====\r\n\r\n- find or create name\r\n- pin name\r\n- find or create reference on the Reference page\r\n- choose reference (tick box)\r\n- choose pinned name (tick box)\r\n- create instance using button that will appear \r\n\r\nStarting on the Reference page\r\n====\r\n\r\n- find or create reference\r\n- pin reference\r\n- find or create name on the Name page\r\n- choose name (tick box)\r\n- choose pinned reference (tick box)\r\n- create instance using button that will appear\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n", name: "Workflow 1 - Create instance from name and reference", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 0, created_by: "creator", marked_up_text: "Marked up text", name: "New blank help_topic created at 12-Jun-2014 04:30pm", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 12, created_by: "creator", marked_up_text: "Searching References\r\n=================\r\n\r\n| Field                             | Tag              | Notes         |\r\n|:-----------------------|:------------|:------------|\r\n| Author                          |        a:          |  link_to 'Author', '#', :class => 'add-to-query', :'data-search-component'=> 'a:'\r\n|APNI ID                         |    apni:         | Does not distinguish between APNI Refs or Pubs link_to\r\n| Created after               |    cr-a:         |    Supply number of days, no wildcards\r\n| Created before            |    cr-b:        |    Supply number of days, no wildcards\r\n| Parent title                   |    pt:            |\r\n| Publication Date         |    pd:           |    Year\r\n|Reference Type            |  rt:               |    Choose from a reference type listed below. No automatic wildcards. Supply enough of the start of the reference type to be distinctive, e.g. rt:b, rt:pe, rt:database r\r\n|Standard abbreviation|  sa:              |\r\n|Title                                |  t:                |\r\n| Updated after              |  cr-a:           |    Supply number of days, no wildcards\r\n| Updated before           | cr-b:           |    Supply number of days, no wildcards\r\n| Volume                         | v:                 |\r\n| Year                              |y:                   |   Supply up to 4 digits.  Only a trailing wildcard is added for you.\r\n\r\n\r\n#### Reference types\r\n\r\n-  book,  \r\n-  database, \r\n-  database record, \r\n-  herbarium annotation, \r\n-  journal, paper, \r\n-  personal communication, \r\n-  section, \r\n- unknown.  \r\n", name: "Fields for Searching References", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 6, created_by: "creator", marked_up_text: "Searching Names\r\n=================\r\n\r\n| Field                             | Tag              | Notes                                                      |\r\n|:--------------------------|:------------|:---------------------------------------|\r\n| Author                               |        a:          |  link_to 'Author', '#', :class => 'add-to-query', :'data-search-component'=> 'a:'\r\n| Author ID                           |    a-id:         | Author ID (used internally)\r\n| Created after                     |    cr-a:         |    Supply number of days, no wildcards\r\n| Created before                  |    cr-b:        |    Supply number of days, no wildcards\r\n| Base Author Name           |   ba:            |\r\n| Ex-Author Name               |   eba:            |\r\n| Ex-Base Author Name     |   ba:            |\r\n| Simple Name                     |   n:            |\r\n| Name  Element                  |   ne:            |\r\n| Name Type                         |  nt:             | Choose from name types listed below. \r\n| Not Name Type                 |  not-nt:     | Choose from name types listed below. \r\n| Name Rank                        |  r:             | Choose from name ranks listed below. \r\n| Sanctioning Author Name |   sa:            |\r\n| Updated after              |  cr-a:           |    Supply number of days, no wildcards\r\n| Updated before           | cr-b:           |    Supply number of days, no wildcards\r\n| Volume                         | v:                 |\r\n| Year                              |y:                   |   Supply up to 4 digits.  Only a trailing wildcard is added for you.\r\n\r\n\r\n#### Name types\r\n\r\n - Scientific\r\n - Sanctioned\r\n - Hybrid\r\n - Hybrid Formula Parents Known\r\n - Hybrid Formula Unknown 2nd Parent\r\n - Named Hybrid\r\n - Named Hybrid Autonym\r\n - Hybrid Autonym\r\n - Intergrade\r\n - Autonym\r\n - Cultivar\r\n - Cultivar Hybrid\r\n - Cultivar Hybrid Formula\r\n - ACRA\r\n - ACRA Hybrid\r\n - PBR\r\n - PBR Hybrid\r\n - Trade\r\n - Trade Hybrid\r\n - Graft / Chimera\r\n - Informal\r\n - Common\r\n\r\n#### Name ranks\r\n\r\n - Species\r\n - Varietas\r\n - Genus\r\n - Subspecies\r\n - Sectio\r\n - Familia\r\n - Forma\r\n - Subgenus\r\n - Ordo\r\n - Series\r\n - Subsectio\r\n - Subseries\r\n - Subvarietas\r\n - Superordo\r\n - Subfamilia\r\n - Subordo\r\n - Tribus\r\n - Subclassis\r\n - Subtribus\r\n - Classis\r\n - Division\r\n - form taxon\r\n - morphological var.\r\n - Subforma\r\n - Nothovarietas\r\n - Regnum\r\n - nothomorph.\r\n - Superspecies\r\n - Nothosubspecies\r\n", name: "Fields for searching Names", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 1, created_by: "creator", marked_up_text: "Marked up text", name: "New blank help_topic created at 03-Jul-2014 05:20pm [Copy]", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 1, created_by: "creator", marked_up_text: "Marked up text", name: "New blank help_topic created at 03-Jul-2014 05:20pm", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 17, created_by: "greg", marked_up_text: "The **NSL Editor** is a web application that allows you to search and edit taxonomic information.\r\n\r\nThat information is organised as:\r\n\r\n- names\r\n- references\r\n- authors, and\r\n- instances\r\n\r\n**Instances** connect **names** to **references** and are sometimes referred to as **usages**.\r\n\r\nNames have an **author** or **authors**, as do references.", name: "About the NSL Editor", sort_order: 1, trash: false, updated_by: "greg" },
  { lock_version: 49, created_by: "creator", marked_up_text: "### Advanced searching\r\n\r\nAdvanced searching is possible in the single search field by using  *search field specifiers*\r\n\r\n#### Search Field Specifiers\r\n\r\nYou can recognise a **search field specifier** because it will precede a search term and end with a colon.\r\ne.g. `a:`  is the search field specifier for the author field.\r\n\r\nSo  `a:bentham` specifies a search for `bentham` as an `author`.\r\n\r\nSeveral search field specifiers can be combined in a single search.   Multiple field specifiers are simply `anded` together in such queries. (There is no option for `or`.)\r\n\r\nHence `a:bentham v:1` is a search for a reference with `author bentham` and `volume 1`. [Try it.](/references/search?utf8=✓&query=a%3Abentham+v%3A1)\r\n\r\n\r\nSome search field specifiers also include a dash.  See the full list of search field specifiers under \r\n\r\n -  [fields for searching names](/help_topics/search?utf8=✓&query=n:fields+for+searching+names)\r\n\r\n - [fields for searching authors](/help_topics/search?utf8=✓&query=n:fields+for+searching+authors)\r\n\r\n - [fields for searching references](/help_topics/search?utf8=✓&query=n:fields+for+searching+references)\r\n\r\n - [fields for searching instances](/help_topics/search?utf8=✓&query=n:fields+for+searching+instances)\r\n\r\nor just look under [fields for searching](/help_topics/search?utf8=✓&query=n:fields+for+searching)\r\n\r\n\r\n", name: "Advanced Searching", sort_order: 35, trash: false, updated_by: "creator" },
  { lock_version: 3, created_by: "creator", marked_up_text: "#### Reference Search\r\n\r\n  * By default, reference searches are run on the reference citation field.\r\n  * The citation field is good for searching because it contains a mix of author, title and other fields.\r\n  * You need match only a fragment of a reference citation to retrieve the record.\r\n  * Other links on the left-hand side tell more about searching.\r\n", name: "Reference search", sort_order: 999, trash: false, updated_by: "creator" },
  { lock_version: 20, created_by: "creator", marked_up_text: "#### Choosing a page\r\n\r\nThe application is made up of separate pages for Names, References, etc.\r\n\r\nThere are links to the pages at the top of the screen in the **navigation bar**.\r\n\r\nThe navigation bar will appear on every page.\r\n\r\nWhatever page you are on is highlighted or underlined on the navigation bar.\r\n\r\nSelect one of the navigation bar links to use that page.\r\n\r\nGood pages to start with are:\r\n\r\n - Names\r\n - References\r\n - Authors\r\n\r\nYou can also send your cursor to the navigation bar by holding the control key down and pressing 'n' or 'N'.\r\n\r\n", name: "Choosing a page", sort_order: 2, trash: false, updated_by: "creator" },
  { lock_version: 19, created_by: "creator", marked_up_text: "#### Simple search\r\n\r\nWhen you type a word into the search field on any page and then press the Enter key you will run a simple search.\r\n\r\nYou can also click, tap or select the \"Search\" button to start a search.\r\n\r\n#### Where does a simple search look?\r\n\r\nSimple searches look at different records, depending on which page you are using:\r\n\r\n- Name searches look in the full names for a match\r\n- Reference searches look in the reference citations\r\n- Author search look in the author names and abbreviations.\r\n\r\n##### Shortcut to the search field\r\n\r\nYou can send your cursor to the search field anytime by holding the Control key down and pressing 'S' or 's'.\r\n\r\n", name: "Simple search", sort_order: 3, trash: false, updated_by: "creator" },
  { lock_version: 9, created_by: "creator", marked_up_text: "#### Search results are limited in number\r\n\r\nSearch results are automatically limited to a fixed number - 100 is the normal limit.\r\n\r\nWe limit search results to avoid long and unexpected delays if you enter a search term that produces hundreds or thousands of results.  We think that consistently fast searching is more important than occasionally retrieving thousands of records.\r\n\r\nYou can retrieve thousands of records if you want to - you can in fact limit your search to any size you like.  Simply add `limit: ` in the search field after  your search term and give the number of results you would like to see.  \r\n\r\nFor example:\r\n\r\n    acacia limit:200\r\n\r\nwould retrieve the first 200 results for acacia on the Name page, and\r\n\r\n    acacia limit: 2\r\n\r\nwould retrieve just the first 2 results.\r\n\r\n\r\n", name: "Search results are limited in number", sort_order: 20, trash: false, updated_by: "creator" }
])
